; Demonstrates layers, sets, trigger vibration, button vibration and modifiers.

[Buttons]
A       =  Enter
B       =  Space
X       =  LShift
Y       =  LCtrl
LB      =  [LayerMode] extrakeys
RB      =  [SetModeToggle] customset
LT      =  [LayerCycle-]
RT      =  [LayerCycle+] 
Back    =  F1
Start   =  Esc
LS      =  LShift
RS      =  MBmouse
Dup     =  Up
Ddown   =  Down
Dleft   =  Left
Dright  =  Right
LSup    =  W
LSdown  =  S
LSleft  =  A
LSright =  D
RSup	=  
RSdown  =  
RSleft  =  
RSright = 
Home	=


[Other]
 ; SendKeysType: 1 = Game mode; 2 = Desktop mode (with windows-style keypress delay + repeat)
SendKeysType             = 1
ShowConfigReloadMessage  = 1
ShowForceQuitMessage     = 1

 ; Timing
TurboRepeatTime          = 50 
ComboAsyncDelay          = 50
SequenceTime             = 50
HoldTime                 = 300
FastPressTime            = 150

 ; Layer/Shift
LayerToCycle             = altkeys, buttons3, keys
ShiftToggleKeyboardValue = 3
KeyboardToggleLayerType  = 0
KeyboardToggleLayerName  = extrakeys


[extrakeys]
A       =  [Turbo] C
Y       =  [Combo] k, b, d, g
X       =  [Fastpress] a, b, c
B       =  [Hold] j, k, l
LB      =  [Sequence] d,f,g,k,u,i,o

[customset]
Y       =  [Turbo] k
A       =  f
B       =  [ComboAsync] h,f,r,d


[set:altkeys]
A       =  [Fastpress] y,u,i
B       =  [ComboAsync] g,u,p,e,r,t
X       =  x

[layer:buttons3]
A       =  c
LB      =  y
RB      =  [Comboasync] r,t,y,a,s

[keys]
A       = D
B       = [Shift] f,g,h,k,l
LB      = [ShiftMode] 3
RB      = [Sequence] j,g,f,r,t,i,o,p



[Wheel]
 ; WheelAnalogMode = 1  Enables progressive behavior when the wheel is assigned to an analog axis. Digital inputs always use step values.
WheelAnalogvalues        = 1

UseSameWheelSpeedLimiter = 1
WheelSpeedLimiter        = 16000

 ;Analog values
WheelSpeedLimiterUp      = 8000
WheelSpeedLimiterDown    = 8000

 ;Digital values
WheelStepUp              = 2
WheelStepDown            = 2

DigitalScrollRepeat      = 1
AnalogScrollRepeat       = 1

[Mouse]
 ; Activating AnalogToMOuse will ignore the buttons assignments in Buttons section and the deadzone values used in the Analogs section for the selected stick.
AnalogToMouse   = 1
Stick           = RS

Sensitivity     = 50
SmoothFactor    = 0.2

LSXaxisInverted = 0
LSYaxisInverted = 0
RSXaxisInverted = 0
RSYaxisInverted = 0

   ; DeadzoneShape; 1: Square; 2: Circular (no rescale); 3: Circular (with rescale).
DeadzoneShape   = 2

; ===SQUARE===
   ; DeadzoneType: 1 = one value for both axes, 2 = one value per axis, 4 = one value per direction
DeadzoneType    = 1

Deadzone        = 2000

Xdeadzone       = 2000
Ydeadzone       = 2000

XleftDeadzone   = 2000
XrightDeadzone  = 2000
YleftDeadzone   = 2000
YrightDeadzone  = 2000


[Analogs]
   ; DeadzoneType: 1 = Global (one value for both sticks and both axes), 2 = PerStick (LS and RS have different deadzones), 4 = PerAxis (X and Y Deadzones per stick), 8 = PerDirection (left/right/up/down deadzones per stick)
DeadzoneType    =  1

   ; Used when DeadzoneType = 1 (Global)
Deadzone        = 4000

   ; Used when DeadzoneType = 2 (PerStick)
LSDeadzone      = 0
RSDeadzone      = 0

   ; Used when DeadzoneType = 4 (PerAxis)
LSXdeadzone     = 0
LSYdeadzone     = 0
RSXdeadzone     = 0
RSYdeadzone     = 0

   ; Used when DeadzoneType = 8 (PerDirection)
LSleftDeadzone  = 0
LSrightDeadzone = 0
LSupDeadzone    = 0
LSdownDeadzone  = 0
RSleftDeadzone  = 0
RSrightDeadzone = 0
RSupDeadzone    = 0
RSdownDeadzone  = 0

LSXaxisInverted = 0
LSYaxisInverted = 0
RSXaxisInverted = 0
RSYaxisInverted = 0


[Vibration]
  ; Enable/Disable rumble effect.
Enabled            = 1
;;; Global only (cannot be overridden per button)
  ; If enabled, LT/RT vibration strength depends on the trigger pressure.
ProgressiveTrigger = 1
  ; If enabled, Strength is used as the default value for both motors.
UseSameStrengthVal = 0
;;;

;;; Default values (can be overridden per button using VibrateButtonN.VariableName)
; Example: VibrateButton3.Style = 1
 ; Style: 0 = Hold, 1 = single, 2 = repeat
Style              = 2
Strength           = 100
LeftMotorStrength  = 100
RightMotorStrength = 100

SingleDuration     = 400
RepeatDuration     = 300
RepeatInterval     = 150
;;;


VibrateButton1     = LT
VibrateButton2     = RT
VibrateButton3     = A
VibrateButton4     = X
VibrateButton5     = Y

VibrateButton1.Style              = 0
VibrateButton1.Motor              = Left

VibrateButton2.Style              = 0
VibrateButton2.Motor              = Right

VibrateButton3.Style              = 2
VibrateButton3.LeftMotorStrength  = 10
VibrateButton3.RightMotorStrength = 10
VibrateButton3.Motor              = Right

VibrateButton4.LeftMotorStrength  = 15
VibrateButton4.RightMotorStrength = 15
VibrateButton4.Motor              = Left
VibrateButton4.RepeatDuration     = 300
VibrateButton4.RepeatInterval     = 500
VibrateButton4.Modifier           = LB

VibrateButton5.Style              = 1
VibrateButton5.Strength           = 10
VibrateButton5.SingleDuration     = 400